# غيّر اسم المجلد حسب اسم مجلدك اللي فيه الملفات (مثلاً: source_folder)
FOLDER="Tepthon/plugins/source-main"

# التأكد أن المجلد موجود
if [ -d "$FOLDER" ]; then
  # نقل كل الملفات والمجلدات من داخل المجلد إلى الجذر
  mv "$FOLDER"/* . 
  mv "$FOLDER"/.* . 2>/dev/null || true

  # حذف المجلد بعد النقل (اختياري)
  rm -rf "$FOLDER"
else
  echo "المجلد $FOLDER غير موجود."
fi
