name: Unzip to Root

on:
  push:
    paths:
      - 'source-main.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip to root
        run: |
          unzip -o source-main.zip -d temp
          shopt -s dotglob
          mv temp/* .
          rm -r temp
