name: Unzip ZIP file

on:
  push:
    paths:
      - 'source-main.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files before unzip
      run: ls -la

    - name: Unzip the file
      run: |
        if [ -f "source-main.zip" ]; then
          unzip -o source-main.zip -d ./
        else
          echo "❌ File not found: source-main.zip"
          exit 1
        fi

    - name: Commit unzipped files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add .
        git commit -m "✅ Unzipped source-main.zip"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
