name: Force Unzip Always

on:
  push:
    branches:
      - main

jobs:
  unzip_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip file
        run: |
          unzip path/to/your-archive.zip -d Tepthon/plugins/

      - name: List contents of plugins folder
        run: ls -la Tepthon/plugins/

      - name: Commit and push unzipped files
        run: |
          if [ -d Tepthon/plugins ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add Tepthon/plugins/
            git commit -m "Add unzipped plugins"
            git push
          else
            echo "❌ Folder Tepthon/plugins/ not found!"
            exit 1
          fi
