name: Force Unzip Always

on:
  push:
    branches:
      - main

jobs:
  unzip_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: فك ضغط source-main.zip
        run: unzip source-main.zip -d Tepthon/plugins/
