name: Force Unzip Always

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip if file exists
        run: |
          if [ -f "plugins.zip" ]; then
            unzip -o plugins.zip -d Tepthon/plugins/
          fi

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit unzipped files
        run: |
          git add Tepthon/plugins/
          git commit -m "Auto unzip plugins" || echo "No changes to commit"
          git push
