name: Force Unzip Always

on:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Unzip file if exists
      run: |
        if [ -f "source-main.zip" ]; then
          unzip -o source-main.zip -d ./
        else
          echo "No ZIP file to unzip."
        fi

    - name: Commit unzipped files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Unzipped source-main.zip"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
